#!/usr/bin/env python3
"""
Training entry point for Sim(3)-aware PlueckerNet with RGB colors on Replica data.

Uses the 9D colored Plücker dataset generated by generate_replica_color_dataset.py.
The network input channel is set to 9; all other architecture is unchanged.

Color dropout is applied during dataset generation (30% of lines per pair),
so this single 9D model handles both colored and colorless inputs at inference.

Workflow:
    # 1. Generate colored dataset (once, ~20 min)
    python generate_replica_color_dataset.py

    # 2. Train
    python train_sim3_replica_rgb.py
"""
import os
import sys
import random
import logging
from datetime import date

import torch
import torch.backends.cudnn as cudnn
from torch.utils.data import DataLoader
from easydict import EasyDict as edict

_PROJECT_ROOT   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLUECKERNET_DIR = os.path.join(_PROJECT_ROOT, '..', 'PlueckerNet')
sys.path.insert(0, os.path.abspath(PLUECKERNET_DIR))
sys.path.insert(0, _PROJECT_ROOT)

from config import get_config
from sim3.dataloader import Sim3PluckerData
from sim3.trainer import Sim3Trainer

ch = logging.StreamHandler(sys.stdout)
logging.getLogger().setLevel(logging.INFO)
logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%m/%d %H:%M:%S', handlers=[ch])


def main(configs):
    train_loader = DataLoader(
        Sim3PluckerData(phase='train', config=configs),
        batch_size=configs.train_batch_size,
        shuffle=True, drop_last=True, num_workers=4,
    )
    val_loader = DataLoader(
        Sim3PluckerData(phase='valid', config=configs),
        batch_size=1, shuffle=False, drop_last=False, num_workers=1,
    )
    trainer = Sim3Trainer(configs, train_loader, val_loader)
    trainer.train()


if __name__ == '__main__':
    configs = get_config()

    configs.dataset          = 'replica_color'
    configs.data_dir         = os.path.join(_PROJECT_ROOT, 'dataset')
    configs.gpu_inds         = 0
    configs.model_nb         = str(date.today())
    configs.train_batch_size = 12
    configs.train_lr         = 1e-3
    configs.train_epoches    = 400
    configs.best_val_metric  = 'avg_inlier_ratio'
    configs.resume_dir       = None
    configs.in_channel       = 9   # 6D Plücker + RGB

    dconfig = vars(configs)
    dconfig['resume'] = None

    logging.info('===> Configurations')
    for k in sorted(dconfig):
        logging.info(f'    {k}: {dconfig[k]}')

    configs = edict(dconfig)

    if configs.train_seed is not None:
        random.seed(configs.train_seed)
        torch.manual_seed(configs.train_seed)
        torch.cuda.manual_seed(configs.train_seed)
        cudnn.deterministic = True

    main(configs)
